# Repository의 Actions 탭에 나타날 Workflow 이름으로 필수 옵션은 아니다.
name: CD

# 트리거를 수행할 브랜치를 지정한다.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# 해당 Workflow의 하나 이상의 Job 목록이다.
jobs:
  # Job 이름으로 , build라는 이름으로 Job이 표시된다.
  build:
    # Runner가 실행되는 환경을 정의하는 부분이다.
    runs-on: ubuntu-latest
    steps:
      # 해당 레포지토리로 check-out 하여
      # 레포지토리에 접근할 수 있는 Action을 불러온다.    
      - name: Checkout source code
      # checkout@v2 는 node12 에서 실행하는 workflow이다.
      # checkout@v3로 바꿔줘야 한다. (node 16)
      # https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
        uses: actions/checkout@v3 # workflow에서 액세스할 수 있도록 저장소를 체크아웃 
      
      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: S3 Deploy
        # 현재 build된 폴더에 접근 후 s3 버킷인 soon-sample-deploy에 파일 업로드
        # --acl bucket-owner-full-control 이 뭔지 알아보기
        run: aws s3 sync ./build s3://soon-sample-deploy/ --acl bucket-owner-full-control
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        # 새로 리소스를 업데이트할 때 기존 캐시 무효화
      - name: Invalidate CloudFront Cache 
        uses: chetan/invalidate-cloudfront-action@master
        env:
          AWS_DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION_ID }}
          PATHS: '/index.html'
        continue-on-error: true
